---
# tasks file for register-dns-client-with-ipa
- name: Import IPA client installation tasks if applicable
  import_tasks: install-ipa-client-on-host.yml
  when:
    - hostvars[inventory_hostname]['install_ipa_client'] is defined
    - hostvars[inventory_hostname]['install_ipa_client'] | bool == true

- name: Import IPA client Registration on host task if applicable
  import_tasks: register-host-with-dns-server.yml
  when:
    - hostvars[inventory_hostname]['register_ipa_client'] is defined
    - hostvars[inventory_hostname]['register_ipa_client'] | bool == true
