---
# tasks file for register-dns-client-with-ipa
- name: Set Permanent hostname for client
  #command: hostnamectl set-hostname {{ hostvars[inventory_hostname]['ansible_hostname'] }}.{{ hostvars[inventory_hostname]['ansible_dns']['search'][0] }}
  command: hostnamectl set-hostname {{ hostvars[inventory_hostname]['ansible_nodename'] }}.{{ hostvars[inventory_hostname]['ansible_dns']['search'][0] }}
  when: 
    - hostvars[inventory_hostname]['set_hostname'] is defined and hostvars[inventory_hostname]['set_hostname'] | bool
  register: hostname_set

- name: Install ipa-client packages
  yum:
    name: "{{ ipa_client_packages }}" 
    state: latest
  when: 
    - hostvars[inventory_hostname]['install_ipa_client'] is defined
    - hostvars[inventory_hostname]['install_ipa_client'] | bool == true
    - hostvars[inventory_hostname]['ansible_os_family'] in ['RedHat']
    - not hostvars[inventory_hostname]['ansible_facts']['pkg_mgr'] in ['apt']
  register: ipa_client_installed

- name: Install ipa-client packages
  apt:
    pkg:
      - freeipa-client
    state: latest
  when: 
    - hostvars[inventory_hostname]['install_ipa_client'] is defined
    - hostvars[inventory_hostname]['install_ipa_client'] | bool == true
    - hostvars[inventory_hostname]['ansible_os_family'] in ['Debian']
    - hostvars[inventory_hostname]['ansible_facts']['pkg_mgr'] in ['apt']
  register: ipa_client_installed

- name: Install IPA Client 
  #shell: "ipa-client-install --domain={{ idm_realm | lower }} --server={{ groups['idm_servers'][0] }} -U -p '{{ idm_admin_username }}' -w '{{ idm_admin_password }}' --enable-dns-updates"
  command: "ipa-client-install --domain={{ idm_realm | lower }} --server={{ groups['idm_servers'][0] }} -U -p '{{ idm_admin_username }}' -w '{{ idm_admin_password }}' --enable-dns-updates"
  when: 
    - hostvars[inventory_hostname]['install_ipa_client'] is defined
    - hostvars[inventory_hostname]['install_ipa_client'] | bool
    - hostvars[inventory_hostname]['ansible_os_family'] in ['RedHat', 'Debian']
  failed_when:
    - ipa_client_configured.rc > 3
    - " 'IPA client is already configured on this system' in ipa_client_configured.stderr  "
  register: ipa_client_configured

- name: Add DNS Zone for the host domain
  ipa_dnszone:
    zone_name: "{{ hostvars[inventory_hostname]['ansible_nodename'].split('.')[1:4] | join('.') }}"
    ipa_host: "{{ idm_host }}"
    ipa_port: "{{ idm_port }}"
    ipa_user: "{{ idm_admin_username }}"
    ipa_pass: "{{ idm_admin_password }}"
    validate_certs: false
  register: ipa_client_zone_added

- name: Add host to IPA 
  ipa_host:
    name: "{{ hostvars[inventory_hostname]['ansible_nodename'] }}"
    ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0]) }}"
    mac_address: "{{ ansible_default_ipv4.macaddress }}"
    ipa_host: "{{ idm_host }}"
    ipa_port: "{{ idm_port }}"
    ipa_user: "{{ idm_admin_username }}"
    ipa_pass: "{{ idm_admin_password }}"
    update_dns: true
    validate_certs: false
  failed_when:
    - ipa_client_added is defined 
    - ipa_client_added.msg is defined 
    - "not 'no modifications to be performed' in ipa_client_added.msg"
  register: ipa_client_added

- name: Print output
  debug:
    var: ipa_client_added

- name: Add DNS Record for client host
  ipa_dnsrecord:
    ipa_host: "{{ idm_host }}"
    ipa_port: "{{ idm_port }}"
    ipa_prot: "https"
    ipa_user: "{{ idm_admin_username }}"
    ipa_pass: "{{ idm_admin_password }}"
    zone_name: "{{ hostvars[inventory_hostname]['ansible_dns']['search'][0] }}"
    record_name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
    record_type: 'A'
    record_value: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0]) }}"
    state: present
    validate_certs: false
  register: ipa_client_dns_added

- name: Add DNS Zone for the reverse lookup address
  ipa_dnszone:
    zone_name: "{{ ((hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[0:3] | join('.') | ipaddr('revdns')).split('.')[1:6] | join('.') }}"
    ipa_host: "{{ idm_host }}"
    ipa_port: "{{ idm_port }}"
    ipa_user: "{{ idm_admin_username }}"
    ipa_pass: "{{ idm_admin_password }}"
    validate_certs: false
  register: ipa_client_reverse_zone_added

- name: Add Reverse Lookup record for client host
  ipa_dnsrecord:
    ipa_host: "{{ idm_host }}"
    ipa_port: "{{ idm_port }}"
    ipa_prot: "https"
    ipa_user: "{{ idm_admin_username }}"
    ipa_pass: "{{ idm_admin_password }}"
    zone_name: "{{ ((hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[0:3] | join('.') | ipaddr('revdns')).split('.')[1:6] | join('.')}}"
    record_name: "{{ (hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[3] | int }}"
    record_type: 'PTR'
    record_value: "{{ hostvars[inventory_hostname]['ansible_nodename'] }}"
    validate_certs: false
  register: ipa_client_revrec_created
