---
# tasks file for register-dns-client-with-ipa
- name: Set Permanent hostname for client
  command: hostnamectl set-hostname {{ hostvars[inventory_hostname]['ansible_hostname'] }}.{{ hostvars[inventory_hostname]['ansible_dns']['search'][0] }}
  when: 
    - hostvars[inventory_hostname]['set_hostname'] is defined and hostvars[inventory_hostname]['set_hostname'] | bool
  register: hostname_set

- name: Add DNS Zone for the host domain
  ipa_dnszone:
    zone_name: "{{ hostvars[inventory_hostname]['ansible_nodename'].split('.')[1:4] | join('.') }}"
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_user: "{{ ipa_admin_username }}"
    ipa_pass: "{{ ipa_admin_password }}"
    validate_certs: false
  register: ipa_client_zone_added

- name: Add Kerberos TXT Record for the DNS Zone for the host domain
  ipa_dnsrecord:
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_prot: "https"
    ipa_user: "{{ ipa_admin_username }}"
    ipa_pass: "{{ ipa_admin_password }}"
    zone_name: "{{ hostvars[inventory_hostname]['ansible_nodename'].split('.')[1:4] | join('.') }}"
    record_name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
    record_type: 'TXT'
    record_value: "{{ hostvars[inventory_hostname]['ansible_nodename'].split('.')[1:4] | join('.') | upper }}"
    state: present
    validate_certs: false
  register: ipa_client_dns_txt_kerberos_added

- name: Add host to IPA 
  ipa_host:
    name: "{{ hostvars[inventory_hostname]['ansible_nodename'] }}"
    ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0]) }}"
    mac_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['macaddress'] }}"
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_user: "{{ ipa_admin_username }}"
    ipa_pass: "{{ ipa_admin_password }}"
    update_dns: true
    validate_certs: false
  failed_when:
    - ipa_client_added is defined 
    - ipa_client_added.msg is defined 
    - "not 'no modifications to be performed' in ipa_client_added.msg"
  register: ipa_client_added

- name: Print output
  debug:
    var: ipa_client_added

- name: Add DNS Record for client host
  ipa_dnsrecord:
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_prot: "https"
    ipa_user: "{{ ipa_admin_username }}"
    ipa_pass: "{{ ipa_admin_password }}"
    zone_name: "{{ hostvars[inventory_hostname]['ansible_dns']['search'][0] }}"
    record_name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
    record_type: 'A'
    record_value: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0]) }}"
    state: present
    validate_certs: false
  register: ipa_client_dns_added

- name: Add DNS Zone for the reverse lookup address
  ipa_dnszone:
    zone_name: "{{ ((hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[0:3] | join('.') | ipaddr('revdns')).split('.')[1:6] | join('.') }}"
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_user: "{{ ipa_admin_username }}"
    ipa_pass: "{{ ipa_admin_password }}"
    validate_certs: false
  register: ipa_client_reverse_zone_added

- name: Add Kerberos TXT Record for the DNS Zone for the host domain
  ipa_dnsrecord:
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_prot: "https"
    ipa_user: "{{ ipa_admin_username }}"
    ipa_pass: "{{ ipa_admin_password }}"
    zone_name: "{{ ((hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[0:3] | join('.') | ipaddr('revdns')).split('.')[1:6] | join('.') }}"
    record_name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
    record_type: 'TXT'
    record_value: "{{ ((hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[0:3] | join('.') | ipaddr('revdns')).split('.')[1:6] | join('.') | upper }}"
    state: present
    validate_certs: false
  register: ipa_client_reverse_txt_kerberos_added

- name: Add Reverse Lookup record for client host
  ipa_dnsrecord:
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_prot: "https"
    ipa_user: "{{ ipa_admin_username }}"
    ipa_pass: "{{ ipa_admin_password }}"
    zone_name: "{{ ((hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[0:3] | join('.') | ipaddr('revdns')).split('.')[1:6] | join('.')}}"
    record_name: "{{ (hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | default(hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][0])).split('.')[3] | int }}"
    record_type: 'PTR'
    record_value: "{{ hostvars[inventory_hostname]['ansible_nodename'] }}"
    validate_certs: false
  register: ipa_client_revrec_created
